### ISSUE TITLE
vmsg plugin iframe in modal not loading

### ISSUE THREAD

**Issue by poVoq** [conversejs/community-plugins#16]
Inside the overlay modal it just shows a standard 404 error message and the following in the browser console:

`TypeError: this.el.querySelector(...).contentWindow.getMp3File is not a function vmsg.js:42:93`

**Comment by deleolajide** [comment]
This is what I get in chrome

![image](https://user-images.githubusercontent.com/110731/69880620-51969580-12c2-11ea-969b-d69be60b3ccd.png)

vmsg-lib.js:426 Error: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.

This is an expected message because my web server does not send back the correct mime http header for wasm

**Comment by poVoq** [comment]
Well it seems like the issue is also the path. I have my plugins under a /plugins/ subdirectory, and in this line it seems tp referr to a path relative to the index.html

https://github.com/conversejs/community-plugins/blob/00d3980e4977d9912a8d8a77d5eb1dd105f618b5/vmsg/vmsg.js#L31

**Comment by deleolajide** [comment]
>and in this line it seems tp referr to a path relative to the index.html

Loading JavaScript dynamically is always problematic with deployment paths. Feel free to modify vmsg.js for your own use. It will difficult to set a generic path that works for all.
